"""empty message

Revision ID: 812cc94a3b70
Revises: 
Create Date: 2023-12-01 01:41:00.169209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812cc94a3b70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('Firstname', sa.String(length=100), nullable=False),
    sa.Column('Secondname', sa.String(length=100), nullable=False),
    sa.Column('phone_num', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Firstname'),
    sa.UniqueConstraint('Secondname'),
    sa.UniqueConstraint('phone_num'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
